name: Build XP Video Engine
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.4.4'
          architecture: 'x86'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Flask==1.1.2 PyYAML==3.12 pyinstaller==3.6
      - name: Build EXE
        run: pyinstaller -w -F --noupx --clean app.py
      - uses: actions/upload-artifact@v4
        with:
          name: app-exe
          path: dist/app.exe
